[ssh]
id_ed25519_pub = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGWfQ0r1CkNeTdLYzsd+LPFCEwlJQN9z++BzF2Oethpn"
id_ed25519_proton_pub = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICDDPkxYuzRBqtndEoRNx/ua5P0KCG9gMsCe77qf+2ie"
id_ed25519_sf_pub = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHSqE07L1RdjIsvs/qRTRT8CjYRX8tjjaQgOdLI0J67O"
gh_action_key_pub = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJc3ZOX/1j5c3hhDtVzckc9cxUybO0HwFvgrF+x+x6rr"
repx_deploy_key_pub = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMvr0gasEFSpj39lzt7Rszj1dsa0H/azCgvFtmM/4rJ2"

id_um_pub = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx um@placeholder"

[nix-serve]
nix-serve-key_pub= "binary-cache-key:YUqGpOpjoO0zIREJVH0PAdjy9L3DWi917Z8/eFqQqy8="

[passwords]
laptop = "$6$dxLcMi321Rg6B7Nu$tRRLCU/7AEFKg7HW56XIKkbtowfyX4uSOq0M8.pKRZIgg6FrdF9o19yAf1mEov.C.SnhSlXG48rmVbVFqtbEn1"
server = "$6$hjsD4y4Iy/9ql6dC$WYxNpnvlx9r6TbGwWcXMqzzsyzh6IvftawYlyvwB4/Zr21UNO5eyj87WB2JqcH.EoO3rmP10P5X/d0b6tNcSh/"

[yubikey]
u2fkey = "emre:7lhDuz2SYxoUD64T2cXDvYj0FalaV8pNnVlzLUmOH8fPCAeXkilsbuNoxrCauiideJ0MtiJbRl/Yvbzy6qXSRA==,+AsrxOEThwWZzChGrzVjEVqBYpd/sREiS6SjbGeuUcGIxAn2i6arArBMTHhOB//2LBvKYMWQ5WC3883VfPq2Rg==,es256,+presence"
gpg_key_id = "B3135E3016E934FF"

gpg_public_key = """-----BEGIN PGP PUBLIC KEY BLOCK-----

mQENBGk2OPIBCADWVX2lsta1uVFx2L2eCtRLIgKww82bj2OfraUyIMiWyLmLSIhh
jtxxDtcc+ds0n2Wj/+WYaggndzySIHXOryRfYYgpnO1UwA37g2HnVU/p0tUMdPmb
Ez8xc4ayBRele2/AEW4eqmPLu6azjAG2fBbylzlOMOFbNzI84ppzy/TBkaiSAaXy
9S23Ql6j/yp1f4KzWjD5N/MyZ8RohuI/93NgMBY20dAezQ3QlFQAI55iQkHDCZvP
ZusBluRvh3uk1RnG13mqhjMOUlD599kpBo2lyfC0vcrqooCkWi4Xs2f5jOAr2K8E
CmNFFahYHYxAA6gbYD4rEaW31yz3TUKxvFIfABEBAAG0KEVtcmUgSGFrYW4gRGVt
aXJsaSA8ZWhkZW1pcmxpQHByb3Rvbi5tZT6JAU4EEwEKADgWIQRqGkLDcXX41gPa
DCuzE14wFuk0/wUCaTY48gIbAwULCQgHAgYVCgkICwIEFgIDAQIeAQIXgAAKCRCz
E14wFuk0/5cyB/sEujIR6l4adDKbP/qeZKDK4qZM9gJZi24MmN8W1DF+HForGxCa
vit2jWOqN6joLJWugkHiytk3+HWINea5oKQms0slRQT4wVWAUGiTGqcrlvoXWTbp
kweEcQppoMBzmRd1D3FsmsZoLPao0nJ0VbFYxzatQhBBS7VooKQ+Zqg6VTHw3NUX
o347gHkeY4pYxGw2/7yXmANaUN6BIjNBoZRFrRNHloAVbVgk/K8XlxCgL0uqLmop
T2QPsaFBy+nkY3WGnT1tWLMu+nsUCCscznvi1QzJnJP8dMUFkowxjBkjn0w37m/Y
bbviw0sq4mFgOeRUdr6Ecl9b2EUKpzT45BekuQENBGk2OPIBCADTfmsIZ7YsdLIs
KxVn7K3W+g3TXOQVzoruAtaE33UwfsSk7YC8bSpLFarBP7jX6egwZk56q5kwwA3W
25aCfrKc+Qc2Kozz0T7CJJ/7xrfhRid0ZnHhwQWdacvMRn87uIMEXhWGWf79vSUF
OGjR8SU3hmDtpT0TeaSHsaRqp871kBZz+DpV+550FWOJGaRqdXZLmrVel6hOzSRI
EeZvTPmaSJLKdqXUd5ew7vRW23pxGBqg619GAJpIpGlqJcylGSE0OV6mNJZEsZD2
Z8e0vgJRRsDsh22e7nmiafPwNo1gSFi9kbXTskIcP4ch5jqg27w7YdJvQ7b2IDxl
kcVkQzhlABEBAAGJATYEGAEKACAWIQRqGkLDcXX41gPaDCuzE14wFuk0/wUCaTY4
8gIbIAAKCRCzE14wFuk0//6DB/sFU+0ffta2v67V7XDJcpauM/0a5mcDo2inuPD3
USxaQRBzREeq5TaUo3x+lwH1Ng+XmvZuDHShMVApaYFkUp/A3f/BTCIjn+DFoOph
zipA6lC6b4TKmEIWoUUWu/CJAHNkUG9B39yK17kRpvNyBERuUeFGGoq7oKQOGdZ1
4Fst+RWIHkCLyxGw/oNRT3sHCBL3BeM5lHio688B33ucKOulEdNP1tuGCi3cOM+J
B8P+C36Xh0SFnTvw9yqNdMfxU3/K4xm3VLTmGtr862vFj6qSRLbxGhDmYyWGa5qh
ynXWcL5Bk4LVXmC1He6JAchc8mjmx9Sch4HpKePtEWCPEXa1uQENBGk2OPIBCADH
6vD1wc5WQR0PcnYnPfxRhjuKSn0Ay3jAVU6uWhV7UYJaYqk3/GiXQCZ/IzZKzaRj
T8ElzWnDY1qOSw13EWr8y6R/EvKur36eN0M0zvBdIibgvYYTbooTbjo8LwDhnKpc
5ZfxXfE96cjQdlUTqQJAU2mKBCY1+tTSJG44Z7TkfaWrix4FnQI2qrDOsRxSN44t
7bOYhRCy/Hrba2AzUROUyJ3oOt4sotDAV91WPgQOy3EdoK6IlJPGJXoIE1v8zDtv
9qmcUyO4lTT9kAC8HfIMV1yAwxph7Sk22ITGBZo7vugTOnY/OzYb1kCsj1SvAxxW
P0ULbZoFwDuCFGFivX/rABEBAAGJATYEGAEKACAWIQRqGkLDcXX41gPaDCuzE14w
Fuk0/wUCaTY48gIbDAAKCRCzE14wFuk0/7INB/4l2ZNLh2cFpwu+Ea4OnXnDVvIM
Wp0dLTppPnh20M/hejI4/H60NZfipQ7+lcLI6AbtgDYk0LIvpJMIc7ZcyP0Bq4s8
XLGgrBcNseSid2BgEKxuM2QZ1i+ZZRJ+/dk3ELsdqt0NHnT+DmkX0KZ8m4Zifxrb
7Ce8daX5GvmvkS8YbIHgiVu+j16Z3qtIv2NLEC5FogliNliCkGEPZs0l6K2OGOH9
jBVTRg/3hrq7xRBDgjT6paQd2XGA+aS5RJCgYQyWpfEifCLtHXuGAMQ5dqySFmtg
N6BYi9+mtbagdI37D5AsaT4Ez6tY9z0hbIjNjztYLowgTIF5YgfkppoyZi7H
=dPrD
-----END PGP PUBLIC KEY BLOCK-----"""

