[ssh]
id_ed25519_pub = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGWfQ0r1CkNeTdLYzsd+LPFCEwlJQN9z++BzF2Oethpn"
id_ed25519_proton_pub = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICDDPkxYuzRBqtndEoRNx/ua5P0KCG9gMsCe77qf+2ie"
id_ed25519_sf_pub = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHSqE07L1RdjIsvs/qRTRT8CjYRX8tjjaQgOdLI0J67O"
gh_action_key_pub = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJc3ZOX/1j5c3hhDtVzckc9cxUybO0HwFvgrF+x+x6rr"

[nix-serve]
nix-serve-key_pub= "binary-cache-key:YUqGpOpjoO0zIREJVH0PAdjy9L3DWi917Z8/eFqQqy8="

[passwords]
laptop = "$6$dxLcMi321Rg6B7Nu$tRRLCU/7AEFKg7HW56XIKkbtowfyX4uSOq0M8.pKRZIgg6FrdF9o19yAf1mEov.C.SnhSlXG48rmVbVFqtbEn1"
server = "$6$hjsD4y4Iy/9ql6dC$WYxNpnvlx9r6TbGwWcXMqzzsyzh6IvftawYlyvwB4/Zr21UNO5eyj87WB2JqcH.EoO3rmP10P5X/d0b6tNcSh/"

[yubikey]
u2fkey = "emre:7lhDuz2SYxoUD64T2cXDvYj0FalaV8pNnVlzLUmOH8fPCAeXkilsbuNoxrCauiideJ0MtiJbRl/Yvbzy6qXSRA==,+AsrxOEThwWZzChGrzVjEVqBYpd/sREiS6SjbGeuUcGIxAn2i6arArBMTHhOB//2LBvKYMWQ5WC3883VfPq2Rg==,es256,+presence"
gpg_key_id = "B3135E3016E934FF"

